### ISSUE TITLE
Consejo: separar en submódulos

### ISSUE THREAD

**Issue by iblancasa** [ButterFlyDevs/StudentsManagementSystem#26]
Teniendo en cuenta que no es una arquitectuara monolítica, os recomendaría que separáseis los distintos microservicios en distintos repositorios y juntarlos todos en uno mediante submódulos. De esta forma hacéis que la gestión del repositorio, hacer los test, desplegar... sea más fácil.

**Comment by juanAFernandez** [comment]
Llevas toda la razón y es una opción que contemplamos al principio, que desechamos rápidamente debido a que aún se estaba decidiendo la configuración del proyecto. Aun así, la naturaleza del proyecto tiene a esa división y **casi con seguridad** se acabará haciendo cuando estudiemos las ventajas, desventajas y la nueva forma de trabajar que implica. Desde luego que con la cantidad de tareas que se han generado quedaría mucho mejor divididas en distintos pequeños proyectos.
