### ISSUE TITLE
Otro enfoque: bases de datos divididas 

### ISSUE THREAD

**Issue by JA-Gonz** [ButterFlyDevs/StudentsManagementSystem#5]
Después de pensarlo y hablarlo con JJ, al final decidimos tirar de bases de datos divididas, al menos, en el proyecto de IV, de cara al proyecto final podemos hacer lo que queramos. Aunque ya que estoy en el escenario, aprovecho para decir que quizás lo mejor sería mantener esta división. Puede ser que para un sólo colegio no sea "menester", pues el sistema en general va a tener como mucho 20-30 personas usandolo simultáneamente, y eso es un ritmo que hasta un Pentium IV puede suportar.

Pero ya sabéis, hay que darle el enfoque a lo grande: varias máquinas, varias bases de datos. Al menos, de cara al proyecto y la presentación de éste al certamen, pues la escalabilidad que tendríamos sería un punto a favor. Luego con los pies en la tierra, si sólo tenemos un colegio y decidimos unificar las dos bass de datos en una misma máquina (OJO, QUE NO EN UNA MISMA BASE DE DATOS), no tenemos más que tocar las API's o pasarelas de comunicación.

Dicho esto, @neon520 hará una base de datos "a la vieja usanza". Introduce datos, guárdalos, y muéstralos. Quizás ya que tienes webapp2 hecho y funcionando para el ejercicio 2, hacer eso es un rato (la parte de la interfaz me refiero).

@juanAFernandez seguirá con su proyecto adelante como si nada de ésto fuera con él (en realidad no se que habéis hablado JJ y tú esta mañana, he pegado la oreja a ratos). No se si al final harás nuestras BD en otra plataforma, como la de Google que tenias pensada. 

Yo haré la base de datos "estadística", y todas las funciones que se nos ocurran de "minería de datos" correrán de mi cuenta hasta que presentemos el proyecto al certamen (amén de otras cosas). Cosas como el tipo "Cuál es el profe con más porcentaje de suspensos" (más bien, un ranking), "cuál es la clase con más partes de incidencias", etc. Como esta parte tira de consultas que pueden ser bastante complejas, se guardarán todos estos datos en una BD aparte (la que haré yo), para no saturar "la clásica".

Dicho esto, faltan algunas cosas que cerrar:

- Frecuencia de procesamiento de datos estadísticos: si la frecuencia es casi en tiempo real, la BD de JAvi estará muy saturada con mi tarea y la suya, si es muy baja, mis estadísticas serán muy pobres. ¿Quizás la solución pueda pasar por replicar la base de datos de Javi cada X hras en una base de datos intermedia, de la cuál sacaré los datos y que estará en "mi máquina"?

- Javi debe programar una API de consulta a tu base de datos. Al igual que yo tengo que programar otra para Juan, para que muestre mis datos. En principio, a la base de datos clásica no le hace falta saber la info estadística.

- Tiggers en bases de datos estadística: serán el pan nuestro de cada día. La estadística no se puede calcular cuando el usuario la pide, sino que ya debe estar calculada de antes, para que el tiempo de respuesta sea el de un misero select de un campo concreto y tabla concreta. (MI mente aún no puede pensar en ORM. HE dicho aún :] )

Ideas, quejas, sugerencias o insultos!

**Comment by JA-Gonz** [comment]
Añado otra cosa y así me pongo pesado: no olvidéis, sobre todo tú @neon520, modificar las descripciones de los README, con las nuevas cositas a hacer.

**Comment by juanAFernandez** [comment]
Por lo que a mi respecta, y esto puede ser completamente independiente de vuestro trabajo para IV, que como ya vais viendo, con una app sencilla os es suficiente, creo que tras la charla con JJ deberíamos orientar el proyecto hacia una Arquitectura basada en Microservicios, debido a que:

1. Un sistema monolítico estilo LAMP (aunque nosotros usemos python) está muy visto y como ha dicho JJ no aportará nada nuevo ni al TFG ni al Certamen de la OSL.
2. He estado investigando el patrón y realmente parece interesante, además de que parece que ofrece como principal ventaja un mantenimiento aislado de las partes (cosa muy buena) y un despliegue y desarrollo mejor, aunque nos cueste más de un quebradero de cabeza.
3. Creo que vamos a aprender bastante más.

Dicho esto estoy intentando hacerme un esquema mental de como podría empezar a descomponerse nuestra app (por sencilla que sea ahora mismo) en módulos y ya empieza a tener sentido algunas cosas.

Por otro lado tenemos que ser **muy abiertos de mente**, y no tomar nada por sentado, es decir, si mañana cambiamos la tecnología por alguna que veamos mejor o que sea más eficiente, no debe suponer ningún problema, ¿hemos venido a jugar no?.

Así que toca investigar mucho, sobretodo por mi parte. <3

Apunte:
Aunque esto se despliegue o no en Google o en cualquier otro proveedor, siempre se podrá probar en forma local, aunque sea más engorroso.

**Comment by juanAFernandez** [comment]
Una buena imagen para entender los [microservicios](https://media.licdn.com/mpr/mpr/shrinknp_750_750/AAEAAQAAAAAAAAIEAAAAJDJmNTE2NDhmLTJhYTctNDA4YS1iM2M0LTEwYmJjODQ5NGViNQ.png).
