### ISSUE TITLE
Seguridad base de datos

### ISSUE THREAD

**Issue by JA-Gonz** [ButterFlyDevs/StudentsManagementSystem#54]
Es necesario cifrar la base de datos. Por ahora, solamente probaremos encriptando la tabla de Credenciales, que recoge enetre otras cosas, el login del profesor. Más adelante sería interesante que podamos cifrar la base de datos entera, ya que trabajamos con información sensible.

Un buen tutorial encontrado y que hace sencillo el encriptado:

http://thinkdiff.net/mysql/encrypt-mysql-data-using-aes-techniques/

**Comment by juanAFernandez** [comment]
Puede ser interesante usar [mysql_real_scape_string()](https://dev.mysql.com/doc/refman/5.5/en/mysql-real-escape-string.html) como un método más de evitar la inyección de código.

**Comment by JA-Gonz** [comment]
Es importante hacerlo, por que la inyección SQL siempre está al acecho...+

Usuario: 46666'#
Contraseña: laquetuquierasTOTALNOLAVAALEER

MEtiendo esto en el formulario, la consulta final acaba siendo...

SELECT * FROM Credenciales WHERE username='46666'#' and password= AES_ENCRYPT('laquetuquierasTOTALNOLAVAALEER',"CLAVESECRETA")

La almohadilla comenta el resto de la consulta, así que será ignorada. La consulta, tras el truncamiento, acaba siendo...

SELECT * FROM Credenciales WHERE username='46666'

Por lo que hacemos el capullo de forma monumental :)
