### ISSUE TITLE
Problemas con la BD en la nube

### ISSUE THREAD

**Issue by neon520** [ButterFlyDevs/StudentsManagementSystem#8]
Al tener una BD en la nube, para tener acceso a ella tenemos que decirle a python cual es el usuario, contraseña, host y nombre de la BD, por lo que tenemos en un repositorio público un acceso a nuestra BD para cualquiera que quiera meterse, además de que si 2 clientes se bajaran el repo accederían a la misma BD.

**Comment by juanAFernandez** [comment]
Normalmente esos datos sensibles están en un fichero aparte, como variables globales o algo así que se importa donde se use que está insertado en el gitignore para que no se suba.  Así no estarán en ningún sitio las contraseñas, sólo las referencias a donde estas están.
